update

diff --git a/.github/workflows/mulesoft.yml b/.github/workflows/mulesoft.yml
--- a/.github/workflows/mulesoft.yml
+++ b/.github/workflows/mulesoft.yml
@@ -217,7 +217,7 @@ jobs:
         uses: actions/download-artifact@v2
         with:
           name: pom
-          
+
       - name: Get secrets for the pipeline
         uses: dmitriybobrovskiy/get-azure-keyvault-secrets@v1.2.0
         with:
@@ -263,6 +263,22 @@ jobs:
         with:
           keyvault: '${{ inputs.keyvault-key }}' # The name of KeyVault in Azure
           secrets_file_path: configurationmap.txt
+
+      - name: Install NodeJs
+        uses: actions/setup-node@v3
+        with:
+          node-version: 18
+  
+      - name: Install Anypoint CLI
+        run: |
+          echo "Install anypoint-cli-v4..."
+          npm install -g anypoint-cli-v4
+          echo ""
+          echo "anypoint-cli-v4 --version: "
+          anypoint-cli-v4 --version
+          echo ""
+          echo "Installing cloudhub-plugin"
+          anypoint-cli-v4 plugins:install anypoint-cli-cloudhub-plugin
 
       - name: Get configuration for the service 
         run: |
@@ -310,11 +326,115 @@ jobs:
           echo "   $confcloudhub"
           echo "Get properties.."
           confproperties=$(echo "$configurationdata" | yq -r ".properties")
-          echo "   $confproperties"
 
           # Replace environment variables
           export deploymentname
-          echo ""
-          echo "Properties with variables substitution"
+          echo "Properties with variable substitution"
           confproperties=$(echo $confproperties | envsubst)
           echo "   $confproperties"
+          echo ""
+
+          start=$(date +%s)
+          echo ""
+          echo "Deployment process start"
+
+          # Get the current status of the service
+          STATUS=$(\
+            anypoint-cli-v4 runtime-mgr cloudhub-application describe \
+            --client_id $ANYPOINT_CLIENT_ID \
+            --client_secret $ANYPOINT_CLIENT_SECRET \
+            --output "json" $deploymentname | jq -r ".status")
+          echo "Deployment status for service: $deploymentname is: $STATUS"
+
+          # Verify if deployment is for update or new application
+          operation="deploy"
+          if [ "$STATUS" != "" ]; then
+            operation="modify"
+          fi
+
+          echo ""
+          echo "Deployment operation for serivce: $deploymentname is: $operation"
+          end=$(date +%s)
+          echo "  Elapsed time: $(($end-$start)) seconds"
+          echo "Deploying...."
+          command="anypoint-cli-v4 runtime-mgr cloudhub-application $operation \
+          --client_id $ANYPOINT_CLIENT_ID \
+          --client_secret $ANYPOINT_CLIENT_SECRET "
+
+          command="$command $confcloudhub $confproperties --output json $deploymentname $jar"
+
+          echo "deployment command: $command"
+          $command
+
+
+          end=$(date +%s)
+          echo ""
+          echo "Deployment finished, verifying the deployment...."
+          echo "  Elapsed time: $(($end-$start)) seconds" 
+
+          iteration=1
+          limit=60
+          while true
+          do 
+            sleep 5
+
+            # Get the current status of the service
+            DEPLOYMENT_INFO=$(\
+              anypoint-cli-v4 runtime-mgr cloudhub-application describe \
+              --client_id $ANYPOINT_CLIENT_ID \
+              --client_secret $ANYPOINT_CLIENT_SECRET \
+              --output "json" $deploymentname)
+            STATUS=$(echo $DEPLOYMENT_INFO | jq -r ".status")
+            UPDATE_STATUS=$(echo $DEPLOYMENT_INFO | jq -r ".deploymentUpdateStatus")  
+            echo "Service: $deploymentname status: $STATUS, updateStatus: $UPDATE_STATUS"
+
+            end=$(date +%s)
+            echo "  Elapsed time: $(($end-$start)) seconds, iteration: $iteration limit: $limit"
+
+            if [ "$operation" = "deploy" ]; then
+                # Create service
+
+                if [ "$STATUS" = "STARTED" ] || [ $iteration -eq $limit ]; then
+                  break # Abandon the while loop.
+                fi
+            else
+                # Update service
+                if [ "$UPDATE_STATUS" = "null" ] || [ "$UPDATE_STATUS" = "DEPLOY_FAILED" ] || [ $iteration -eq $limit ]; then
+                  break # Abandon the while loop.
+                fi
+            fi
+
+            iteration=$(( $iteration + 1 ))
+          done
+
+
+
+
+          # Verify if service was successfully deployed 
+          if [ "$operation" = "deploy" ]; then
+
+            # Create new service
+            if [ "$STATUS" != "STARTED" ]; then
+              echo "Error: The service was not deployed in the expected time, review logs"
+              echo "  example: anypoint-cli-v4 runtime-mgr cloudhub-application download-logs {APP-NAME}"
+              echo "The expected iterations were 44 but the proccess reached the limit: $limit"
+
+              exit 1 # terminate and indicate error
+            else
+              echo "Deployment successful.."
+            fi
+          else
+            # Update service
+            if [ "$UPDATE_STATUS" = "DEPLOY_FAILED" ]; then
+              echo "Error: There were errors while deploying the service"
+              exit 1 # terminate and indicate error
+            elif [ $iteration -eq $limit ]; then
+              echo "Error: The service was not deployed in the expected time, review logs"
+              echo "  example: anypoint-cli-v4 runtime-mgr cloudhub-application download-logs {APP-NAME}"
+              echo "The expected iterations were 44 but the proccess reached the limit: $limit"
+
+              exit 1 # terminate and indicate error
+            else
+              echo "Deployment successful.."
+            fi
+          fi
